language: ruby
rvm:
- 2.1

install:
 - bundle install
 - npm install

before_script: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    mkdir -p _site
    git clone -q https://ianlintner-wf:$GITHUB_API_KEY@github.com/ianlintner-wf/til.git -b gh-pages _site
    echo '_site directory created'
    echo 'preparing to build _site...'
  fi

script: grunt build

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    echo 'attempting run rake deploy...'
    rake deploy
  fi

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

