language: ruby
rvm:
- 2.1

install:
 - bundle install
 - npm install


script: cd "$TRAVIS_BUILD_DIR" && mkdir _site && git clone -q https://ianlintner-wf:$GITHUB_API_KEY@github.com/ianlintner-wf/til.git -b gh-pages _site
script: grunt build


after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd _site
    git add -A
    git -c user.name='travis' -c user.email='travis' commit -m 'automated build'

    git remote add ghub https://ianlintner-wf:$GITHUB_API_KEY@github.com/ianlintner-wf/til.git

    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q ghub &2>/dev/null
    echo 'git push complete'
    cd "$TRAVIS_BUILD_DIR"
  fi

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

