language: ruby
rvm:
- 2.1

install:
 - bundle install
 - npm install

script: grunt build

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd _site
    git init
    git checkout -b gh-pages
    git add -A
    git -c user.name='travis' -c user.email='travis' commit -m init

    git remote rm origin
    git remote add origin https://ianlintner-wf:$GITHUB_API_KEY@github.com/ianlintner-wf/til.git

    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

